
import Header from "./components/header.js";
import { FavoritesProvider } from './context/FavoritesContext';
 

export const metadata = {
  title: "PlayTv",
  description: "Generated by create next app",
};
 
export default function RootLayout({ children }) {
  return (
    <div>
        <Header/>
        <FavoritesProvider>
        {children}
        </FavoritesProvider>
        </div>

  );
}