import { Open_Sans } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import Header from "./components/header.js";
import { FavoritesProvider } from './context/FavoritesContext';

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300","600","700"]
});

export const metadata = {
  title: "PlayTv",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <FavoritesProvider>
        {children}
        </FavoritesProvider>
      </body>
    </html>
  );
}
